
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: System
    password: 1234
    driver-class-name: oracle.jdbc.OracleDriver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      idle-timeout: 60000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: HikariCorePool
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: select * from information_schema.tables limit 1

logging:
  config:
    classpath: log4j2.yaml

mybatis:
  config-location: classpath:mybatis-config.xml

#  jpa:
#    show-sql: true
#    hibernate.ddl-auto: none

