
#spring:
#  datasource:
#    url: jdbc:oracle:thin:@localhost:1521/xe
#    username: System
#    password: 1234
#    driver-class-name: oracle.jdbc.OracleDriver
#    type: com.zaxxer.hikari.HikariDataSource
#    hikari:
#      minimum-idle: 5
#      idle-timeout: 60000
#      maximum-pool-size: 10
#      auto-commit: true
#      pool-name: HikariCorePool
#      max-lifetime: 1800000
#      connection-timeout: 30000
#      connection-test-query: select * from information_schema.tables limit 1
##  security:
##      user:
##          name: user
##          password: 1234
#
#  mybatis:
#    config-location: classpath:mybatis-config.xml
#

server:
  port: 9090

  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

logging:
  config:
    classpath: log4j2.yaml

#spring:
#  thymeleaf:
#    prefix: classpath:/templates/
#    suffix: .html

#spring:
#  jackson:
#    serialization:
#      fail-on-empty-beans: false
#  main:
#    allow-bean-definition-overriding: true

# Feign Client 설정


# 원격 서비스 URL 설정
#terms:
#  url: http://localhost:8080/api/v1/terms




